title: TCH's Lab Book 
author:
  name: tch1001
  email: tanchienhao@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Just a big nerd for almost everything STEM. 

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: github,         user_url: "https://github.com/tch1001" }
    # - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    - { platform: instagram,      user_url: "https://www.instagram.com/tch1001" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/tan-chien-hao-49abb1185" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/4980420/chien-hao-tan" }
    - { platform: telegram,       user_url: "https://t.me/tch1001" }
    - { platform: youtube,        user_url: "https://www.youtube.com/tanchienhao" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
